@extends('layouts_app')
@section('content')
@php
    $stageLabels = ['received' => 'Received', 'pending' => 'Received', 'washing' => 'Washing', 'in-progress' => 'Washing', 'drying' => 'Drying', 'ironing' => 'Ironing', 'folding' => 'Folding', 'ready_for_pickup' => 'Ready for Pickup', 'ready' => 'Ready for Pickup', 'claimed' => 'Claimed', 'delivered' => 'Claimed', 'cancelled' => 'Cancelled'];
    $dailyMax = max(1, $dailyTrend->max('count') ?? 0);
    $chartPoints = $dailyTrend->values()->map(fn ($day, $index) => [
        'x' => 50 + ($index * 100),
        'y' => 140 - ($day['count'] / $dailyMax * 100),
        ...$day,
    ]);
    $stageFilterAliases = ['pending' => 'received', 'in-progress' => 'washing', 'ready' => 'ready_for_pickup', 'delivered' => 'claimed'];
    $dateQuery = array_filter(['from' => $from, 'to' => $to]);
@endphp
<div class="mb-7 flex flex-wrap items-center justify-between gap-4">
    <div><p class="mb-1 text-sm text-slate-500">Operational overview — Trowa Laundry</p><h1 class="text-3xl font-bold text-slate-900">Admin Dashboard</h1></div>
    <div class="flex flex-wrap items-center justify-end gap-3">
        <form method="GET" action="{{ route('dashboard') }}" class="flex flex-wrap items-end gap-2">
            <label class="text-xs font-medium text-slate-600">From<input type="date" name="from" value="{{ $from }}" class="field mt-1 w-36 px-2 py-2 text-xs"></label>
            <label class="text-xs font-medium text-slate-600">To<input type="date" name="to" value="{{ $to }}" class="field mt-1 w-36 px-2 py-2 text-xs"></label>
            <button class="btn-primary px-3 py-2 text-xs">Apply</button>
            @if($from || $to)<a href="{{ route('dashboard') }}" class="btn-secondary px-3 py-2 text-xs">Clear</a>@endif
        </form>
        <span class="rounded-full border border-amber-200 bg-amber-50 px-3 py-1 text-xs font-semibold text-amber-700">Administrator Access</span>
    </div>
</div>
<p class="-mt-4 mb-5 text-right text-xs text-slate-500">{{ $from || $to ? 'KPIs use the selected order/expense/payment date range.' : 'KPIs show all-time totals; the line graph shows the last 7 days.' }}</p>
<div class="mb-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
    @foreach([['₱','Completed order revenue','₱'.number_format((float) $revenue,2),'Claimed/completed orders',route('reports',$dateQuery)],['−','Recorded expenses','₱'.number_format((float) $expensesTotal,2),'All recorded expenses',route('expenses.index',$dateQuery)],['=','Estimated net profit','₱'.number_format((float) $revenue - (float) $expensesTotal,2),'Revenue less expenses',route('reports',$dateQuery)],['!','Balances due','₱'.number_format((float) $balancesDue,2),'Outstanding customer balances',route('payments.index',$dateQuery)],['▣','Unclaimed orders',$unclaimedOrders,'Ready for pickup',route('schedule.index',['status'=>'ready_for_pickup',...$dateQuery])],['▤','All orders',$orders->count(),$from || $to ? 'Orders in selected range' : 'All-time orders',route('orders.index',$dateQuery)],['♟','Active staff',$team->where('role','staff')->count(),'Staff accounts',route('reports',$dateQuery)],['⚠','Low-stock items',$lowStockItems->count(),'At or below reorder threshold',route('inventory.index')]] as [$icon,$label,$value,$hint,$url])
        <a href="{{ $url }}" class="panel flex gap-4 p-5 transition hover:-translate-y-0.5 hover:border-brand-200 hover:shadow-md focus:outline-none focus:ring-2 focus:ring-brand-500"><span class="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-brand-50 text-lg">{{ $icon }}</span><span><span class="block text-xs uppercase tracking-wide text-slate-500">{{ $label }}</span><span class="block font-display text-2xl font-bold text-slate-900">{{ $value }}</span><span class="block text-xs text-slate-400">{{ $hint }} · View details →</span></span></a>
    @endforeach
</div>
@if($lowStockItems->isNotEmpty())<a href="{{ route('inventory.index') }}" class="mb-5 block rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><strong>Low-stock alert:</strong> @foreach($lowStockItems as $item){{ $item->name }} ({{ $item->quantity_on_hand }} {{ $item->unit }})@if(!$loop->last), @endif @endforeach · Manage Inventory →</a>@endif
<div class="mb-5 grid gap-5 lg:grid-cols-2">
    <section class="panel p-5"><h2 class="mb-4 font-display text-lg font-semibold">Orders by Stage <span class="text-xs font-normal text-slate-400">· Select a stage to view orders</span></h2><div class="space-y-3">@foreach($stageLabels as $status => $label)@if($orderStages->has($status))<a href="{{ route('schedule.index',['status'=>$stageFilterAliases[$status] ?? $status,...$dateQuery]) }}" class="group flex items-center gap-3 rounded-lg p-1 text-sm hover:bg-brand-50 focus:outline-none focus:ring-2 focus:ring-brand-500"><span class="w-32 shrink-0 group-hover:text-brand-700">{{ $label }}</span><span class="h-2 flex-1 rounded-full bg-slate-100"><span class="block h-2 rounded-full bg-brand-500 group-hover:bg-brand-600" style="width:{{ max(4, $orders->count() ? $orderStages->get($status) / $orders->count() * 100 : 0) }}%"></span></span><strong>{{ $orderStages->get($status) }}</strong></a>@endif @endforeach</div></section>
    <section class="panel p-5"><h2 class="mb-1 font-display text-lg font-semibold">Daily Order Volume</h2><p class="mb-3 text-xs text-slate-500">Select a point to view that day’s orders. {{ \Carbon\Carbon::parse($dailyTrend->first()['date'])->format('M j') }} – {{ \Carbon\Carbon::parse($dailyTrend->last()['date'])->format('M j, Y') }}</p><div class="overflow-x-auto pb-2"><svg viewBox="0 0 700 180" role="img" aria-labelledby="daily-orders-title daily-orders-description" class="h-48 w-full min-w-[560px]"><title id="daily-orders-title">Daily order volume line graph</title><desc id="daily-orders-description">Clickable points show the number of orders created on each date.</desc><line x1="40" y1="140" x2="660" y2="140" stroke="#cbd5e1" stroke-width="1"/><line x1="40" y1="90" x2="660" y2="90" stroke="#e2e8f0" stroke-width="1"/><line x1="40" y1="40" x2="660" y2="40" stroke="#e2e8f0" stroke-width="1"/><polyline points="{{ $chartPoints->map(fn ($point) => $point['x'].','.$point['y'])->implode(' ') }}" fill="none" stroke="#14b8a6" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/>@foreach($chartPoints as $point)<a href="{{ route('schedule.index',['date'=>$point['date']]) }}" aria-label="View {{ $point['count'] }} orders from {{ \Carbon\Carbon::parse($point['date'])->format('F j, Y') }}"><circle cx="{{ $point['x'] }}" cy="{{ $point['y'] }}" r="7" fill="#0d9488" stroke="white" stroke-width="3"><title>{{ $point['count'] }} orders · {{ \Carbon\Carbon::parse($point['date'])->format('M j, Y') }}</title></circle></a><text x="{{ $point['x'] }}" y="165" text-anchor="middle" fill="#64748b" font-size="11">{{ $point['label'] }}</text><text x="{{ $point['x'] }}" y="{{ $point['y'] - 14 }}" text-anchor="middle" fill="#0f172a" font-size="11" font-weight="600">{{ $point['count'] }}</text>@endforeach</svg></div></section>
</div>
<div class="mb-5 grid gap-5 lg:grid-cols-2">
    <section class="panel p-5"><h2 class="mb-4 font-display text-lg font-semibold">Payments by Method</h2><div class="space-y-3">@forelse($paymentsByMethod as $method => $amount)<a href="{{ route('payments.index',['method'=>$method,...$dateQuery]) }}" class="flex items-center justify-between rounded-lg border-b border-slate-100 pb-2 text-sm hover:bg-brand-50 focus:outline-none focus:ring-2 focus:ring-brand-500"><span class="capitalize">{{ $method }} <span class="text-brand-600">View →</span></span><strong>₱{{ number_format($amount, 2) }}</strong></a>@empty<p class="text-sm text-slate-500">No payment records yet.</p>@endforelse</div></section>
    <section class="panel p-5"><div class="mb-4 flex items-center justify-between"><h2 class="font-display text-lg font-semibold">Recent Orders</h2><a href="{{ route('orders.index') }}" class="text-sm font-semibold text-brand-600">All orders</a></div><div class="space-y-3">@forelse($orders->take(6) as $order)<a href="{{ route('orders.show', $order) }}" class="flex items-center justify-between gap-3 border-b border-slate-100 pb-3 text-sm last:border-0"><span><strong>{{ $order->order_number ?? 'TL-'.$order->id }}</strong><small class="block text-slate-500">{{ $order->customer_name }}</small></span><span class="text-right"><strong>₱{{ number_format((float) $order->total_price,2) }}</strong><small class="block capitalize text-slate-500">{{ str_replace('_',' ',$order->status) }}</small></span></a>@empty<p class="text-sm text-slate-500">No orders yet.</p>@endforelse</div></section>
</div>
<div class="panel p-5"><div class="mb-4 flex items-center justify-between"><h2 class="font-display text-lg font-semibold">Team Overview</h2><a href="{{ route('reports') }}" class="text-sm font-semibold text-brand-600">View Reports</a></div><div class="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">@foreach($team as $member)<div class="rounded-lg bg-slate-50 p-3 text-sm"><span class="font-semibold">{{ $member->name }}</span><span class="block text-xs capitalize text-slate-500">{{ $member->role }}</span></div>@endforeach</div></div>
@endsection
