@extends('layouts_app')
@section('content')
<div class="mb-6"><p class="text-sm font-medium text-brand-600">Admin operations</p><h1 class="text-3xl font-bold">Inventory</h1><p class="text-sm text-slate-500">Manage consumables, stock movements, and service usage recipes.</p></div>
@php($lowStockItems = $items->filter(fn ($item) => $item->is_active && (float) $item->quantity_on_hand <= (float) $item->low_stock_threshold))
@if($lowStockItems->isNotEmpty())<div class="mb-5 rounded-xl border border-amber-200 bg-amber-50 p-4 text-amber-900"><h2 class="font-semibold">Low-stock alerts</h2><ul class="mt-2 list-inside list-disc text-sm">@foreach($lowStockItems as $item)<li>{{ $item->name }}: {{ $item->quantity_on_hand }} {{ $item->unit }} remaining (threshold {{ $item->low_stock_threshold }} {{ $item->unit }})</li>@endforeach</ul></div>@endif
<div class="grid gap-5 xl:grid-cols-[1fr_1.5fr]">
    <div class="panel p-5"><h2 class="mb-4 font-display text-lg font-semibold">Add Consumable</h2><form method="POST" action="{{ route('inventory.store') }}" class="space-y-3">@csrf<label class="block text-sm font-medium">Item name<input name="name" class="field mt-1" placeholder="Detergent" required></label><div class="grid grid-cols-3 gap-2"><label class="text-sm font-medium">Unit<input name="unit" class="field mt-1" placeholder="kg / L / pcs" required></label><label class="text-sm font-medium">Opening stock<input name="quantity_on_hand" type="number" min="0" step="0.001" class="field mt-1" value="0" required></label><label class="text-sm font-medium">Low threshold<input name="low_stock_threshold" type="number" min="0" step="0.001" class="field mt-1" value="0" required></label></div><button class="btn-primary w-full">Add Inventory Item</button></form></div>
    <div class="panel p-5"><h2 class="mb-4 font-display text-lg font-semibold">Automatic Service Consumption</h2><p class="mb-3 text-xs text-slate-500">Configure the consumable quantity used per machine load. New orders deduct mapped items automatically.</p><form method="POST" action="{{ route('inventory.usage.store') }}" class="grid gap-3 sm:grid-cols-3">@csrf<select name="service_id" class="field" required><option value="">Service</option>@foreach($services as $service)<option value="{{ $service->id }}">{{ $service->name }}</option>@endforeach</select><select name="inventory_item_id" class="field" required><option value="">Consumable</option>@foreach($items->where('is_active', true) as $item)<option value="{{ $item->id }}">{{ $item->name }} ({{ $item->unit }})</option>@endforeach</select><div class="flex gap-2"><input name="quantity_per_load" type="number" min="0.001" step="0.001" class="field" placeholder="Qty/load" required><button class="btn-primary">Save</button></div></form><div class="mt-4 space-y-2">@forelse($usages as $usage)<div class="flex items-center justify-between border-t border-slate-100 pt-2 text-sm"><span>{{ $usage->service->name }} uses {{ $usage->quantity_per_load }} {{ $usage->inventoryItem->unit }} {{ $usage->inventoryItem->name }} / load</span><form method="POST" action="{{ route('inventory.usage.destroy', $usage) }}">@csrf @method('DELETE')<button class="text-red-600">Remove</button></form></div>@empty<p class="text-sm text-slate-500">No service consumption configured.</p>@endforelse</div></div>
</div>
<div class="mt-5 space-y-4"><h2 class="font-display text-xl font-semibold">Stock on Hand and Movement Ledger</h2>
@foreach($items as $item)
<details class="panel overflow-hidden" open><summary class="flex cursor-pointer list-none flex-wrap items-center justify-between gap-3 p-4"><span class="font-semibold">{{ $item->name }} <small class="font-normal text-slate-500">({{ $item->unit }})</small></span><span class="flex items-center gap-3"><span class="font-display text-lg {{ (float) $item->quantity_on_hand <= (float) $item->low_stock_threshold ? 'text-amber-700' : 'text-slate-900' }}">{{ $item->quantity_on_hand }}</span><span class="text-xs text-slate-500">Threshold {{ $item->low_stock_threshold }}</span></span></summary>
<div class="border-t border-slate-100 p-4"><form method="POST" action="{{ route('inventory.movement', $item) }}" class="mb-4 grid gap-2 sm:grid-cols-[160px_160px_1fr_auto]">@csrf<select name="movement_type" class="field"><option value="stock_in">Stock received</option><option value="stock_out">Manual usage</option><option value="adjustment">Set counted balance</option></select><input name="quantity" type="number" min="0.001" step="0.001" class="field" placeholder="Quantity / new balance" required><input name="notes" class="field" placeholder="Supplier, reason, invoice, etc."><button class="btn-secondary">Record Movement</button></form>
<div class="overflow-x-auto"><table class="w-full text-left text-xs"><thead class="text-slate-500"><tr><th class="py-2">Date</th><th>Movement</th><th>Change</th><th>Order</th><th>Recorded by</th><th>Notes</th></tr></thead><tbody>@forelse($item->movements->take(10) as $movement)<tr class="border-t border-slate-100"><td class="py-2">{{ $movement->created_at->format('Y-m-d H:i') }}</td><td>{{ str_replace('_', ' ', ucfirst($movement->movement_type)) }}</td><td>{{ $movement->quantity_change }} {{ $item->unit }}</td><td>{{ $movement->order?->order_number ?? '—' }}</td><td>{{ $movement->recordedBy->name }}</td><td>{{ $movement->notes ?? '—' }}</td></tr>@empty<tr><td colspan="6" class="py-3 text-slate-500">No stock movements recorded.</td></tr>@endforelse</tbody></table></div></div></details>
@endforeach
</div>
@endsection
