@extends('layouts_app')
@section('content')
<div class="mb-6"><a href="{{ route('orders.show', $order) }}" class="text-sm text-brand-600 hover:underline">← Back to order</a><h1 class="mt-2 text-3xl font-bold">Correct Order Details</h1><p class="text-sm text-slate-500">Corrections are recorded in the order audit history. Existing payment records are retained.</p></div>
<form method="POST" action="{{ route('orders.update-details', $order) }}" class="panel space-y-6 p-5">@csrf @method('PUT')
    <div><h2 class="mb-3 font-display font-semibold">Customer and Laundry</h2><div class="grid gap-3 md:grid-cols-3"><label class="text-sm font-medium">Customer<select name="customer_id" class="field mt-1" required>@foreach($customers as $customer)<option value="{{ $customer->id }}" @selected($customer->id === $order->customer_id)>{{ $customer->name }}</option>@endforeach</select></label><label class="text-sm font-medium">Weight in kilograms<input name="weight_kg" type="number" min="0.01" step="0.01" value="{{ $order->weight_kg }}" class="field mt-1" required></label><div class="rounded-lg bg-brand-50 p-3 text-sm"><p class="text-xs text-brand-700">Loads are recalculated automatically</p><strong>CEILING(weight ÷ 8 kg)</strong></div></div></div>
    <div><h2 class="mb-3 font-display font-semibold">Laundry Services</h2><div class="grid gap-2 md:grid-cols-2">@foreach($services as $service)<label class="flex items-center gap-3 rounded-lg border border-slate-200 p-3 text-sm"><input type="checkbox" name="service_ids[]" value="{{ $service->id }}" @checked($order->orderServices->contains('service_id', $service->id))><span class="flex-1">{{ $service->name }}</span><span class="text-slate-500">₱{{ number_format((float) ($service->price_per_load ?? $service->price), 2) }}/load</span></label>@endforeach</div></div>
    <div><h2 class="mb-3 font-display font-semibold">Item Quantities</h2><div id="edit-items" class="space-y-2">@forelse($order->itemDetails as $index => $item)<div class="grid gap-2 sm:grid-cols-2"><input name="item_details[{{ $index }}][item_name]" value="{{ $item->item_name }}" class="field" placeholder="Item name"><input name="item_details[{{ $index }}][quantity]" value="{{ $item->quantity }}" type="number" min="1" class="field" placeholder="Quantity"></div>@empty<div class="grid gap-2 sm:grid-cols-2"><input name="item_details[0][item_name]" class="field" placeholder="Item name"><input name="item_details[0][quantity]" type="number" min="1" class="field" placeholder="Quantity"></div>@endforelse</div></div>
    <label class="block text-sm font-medium">Reason for correction<textarea name="reason" class="field mt-1" rows="3" required placeholder="Explain why this order is being corrected."></textarea></label>
    <div class="flex justify-end gap-3"><a href="{{ route('orders.show', $order) }}" class="btn-secondary">Cancel</a><button class="btn-primary">Save Correction</button></div>
</form>
@endsection
