@extends('layouts_app')

@section('content')
@php
    $totalPaid = (float) $order->amount_paid;
    $balance = max(0, (float) $order->total_price - $totalPaid);
    $labels = ['received' => 'Received', 'washing' => 'Washing', 'drying' => 'Drying', 'ironing' => 'Ironing', 'folding' => 'Folding', 'ready_for_pickup' => 'Ready for Pickup', 'claimed' => 'Claimed', 'cancelled' => 'Cancelled'];
    $availableStatuses = $order->nextStatuses();
    $nextStatus = collect($availableStatuses)->first(fn ($availableStatus) => $availableStatus !== 'cancelled');
@endphp
<div class="mb-6 flex items-start justify-between gap-4">
    <div><a href="{{ route('schedule.index') }}" class="text-sm text-brand-600 hover:underline">← Back to orders</a><h1 class="mt-2 text-3xl font-bold">{{ $order->order_number ?? 'TL-'.$order->id }}</h1><p class="text-sm text-slate-500">{{ $order->customer?->name ?? $order->customer_name }}</p></div>
    @if(auth()->user()->role === 'admin')<a href="{{ route('orders.edit', $order) }}" class="btn-secondary">Edit Order</a>@endif
    <span class="badge bg-blue-100 text-blue-700">{{ $labels[$order->status] ?? ucfirst($order->status) }}</span>
</div>
<div class="grid gap-5 lg:grid-cols-3">
    <div class="space-y-5 lg:col-span-2">
        <div class="panel p-5"><h2 class="mb-4 font-display text-lg font-semibold">Order Details</h2><div class="grid gap-4 sm:grid-cols-3"><div><p class="text-xs uppercase text-slate-500">Customer</p><p class="font-semibold">{{ $order->customer?->name ?? $order->customer_name }}</p></div><div><p class="text-xs uppercase text-slate-500">Weight / Loads</p><p class="font-semibold">{{ $order->weight_kg }} kg · {{ $order->number_of_loads }} load(s)</p></div><div><p class="text-xs uppercase text-slate-500">Total amount</p><p class="font-semibold">₱{{ number_format((float) $order->total_price, 2) }}</p></div></div><div class="mt-5 border-t border-slate-100 pt-4"><h3 class="mb-3 font-semibold">Laundry Item Details</h3><div class="space-y-2">@forelse($order->itemDetails as $item)<div class="flex justify-between text-sm"><span>{{ $item->item_name }}</span><span>{{ $item->quantity }} item(s)</span></div>@empty<p class="text-sm text-slate-500">No individual item details recorded.</p>@endforelse</div></div><div class="mt-5 border-t border-slate-100 pt-4"><h3 class="mb-3 font-semibold">Services</h3><div class="space-y-2">@foreach($order->orderServices as $line)<div class="flex justify-between text-sm"><span>{{ $line->service?->name }} · {{ $line->loads }} load(s)</span><span>₱{{ number_format((float) $line->subtotal, 2) }}</span></div>@endforeach</div></div></div>
        @if($availableStatuses)<div class="panel p-5"><h2 class="mb-4 font-display text-lg font-semibold">Update Status</h2><p class="mb-3 text-xs text-slate-500">The next action follows the selected services for this order.</p><div class="flex flex-wrap items-end gap-3">@if($nextStatus)<form method="POST" action="{{ route('orders.status.update', $order) }}" class="flex flex-1 flex-wrap items-end gap-3">@csrf<input type="hidden" name="status" value="{{ $nextStatus }}"><label class="min-w-48 flex-1 text-sm font-medium">Optional note<input name="notes" class="field mt-1" placeholder="Add a note about this status change"></label><button class="btn-primary whitespace-nowrap">Move to {{ $labels[$nextStatus] }} <span aria-hidden="true">→</span></button></form>@endif @if(in_array('cancelled', $availableStatuses, true))<form method="POST" action="{{ route('orders.status.update', $order) }}" onsubmit="return confirm('Cancel this order? This action cannot be undone.');">@csrf<input type="hidden" name="status" value="cancelled"><button class="rounded-lg px-3 py-2 text-sm font-semibold text-red-700 hover:bg-red-50">Cancel Order</button></form>@endif</div></div>@endif
        <div class="panel p-5"><h2 class="mb-4 font-display text-lg font-semibold">Status History</h2><div class="space-y-4">@forelse($order->statusHistories as $history)<div class="flex gap-3"><span class="mt-1 h-2 w-2 rounded-full bg-brand-500"></span><div><p class="font-semibold">{{ $labels[$history->status] ?? ucfirst($history->status) }}</p><p class="text-xs text-slate-500">{{ $history->created_at->format('M d, Y h:i A') }} · {{ $history->changedBy->name }}</p>@if($history->notes)<p class="mt-1 text-sm text-slate-600">{{ $history->notes }}</p>@endif</div></div>@empty<p class="text-sm text-slate-500">No status history yet.</p>@endforelse</div></div>
    </div>
    <div class="space-y-5">
        <div class="panel p-5"><h2 class="mb-4 font-display text-lg font-semibold">Payment Summary</h2><dl class="space-y-2 text-sm"><div class="flex justify-between"><dt>Total</dt><dd>₱{{ number_format((float) $order->total_price, 2) }}</dd></div><div class="flex justify-between"><dt>Net paid</dt><dd>₱{{ number_format($totalPaid, 2) }}</dd></div><div class="flex justify-between font-semibold"><dt>Remaining balance</dt><dd>₱{{ number_format($balance, 2) }}</dd></div></dl><span class="mt-3 inline-flex badge {{ $order->payments->contains('payment_status', 'refunded') && $totalPaid <= 0 ? 'bg-red-100 text-red-700' : ($balance <= 0 ? 'bg-emerald-100 text-emerald-700' : ($totalPaid > 0 ? 'bg-amber-100 text-amber-700' : 'bg-slate-100 text-slate-600')) }}">{{ $order->payments->contains('payment_status', 'refunded') && $totalPaid <= 0 ? 'Refunded' : ($balance <= 0 ? 'Paid' : ($totalPaid > 0 ? 'Partially Paid' : 'Pending')) }}</span></div>
        @if($balance > 0)<div class="panel p-5"><h2 class="mb-4 font-display text-lg font-semibold">Add Payment</h2><p class="mb-3 text-xs text-slate-500">Maximum payment: ₱{{ number_format($balance, 2) }}</p><form method="POST" action="{{ route('orders.payments.store', $order) }}" class="space-y-3">@csrf<label class="block text-sm font-medium">Amount<input name="amount" type="number" min="0.01" max="{{ $balance }}" step="0.01" class="field mt-1" required></label><label class="block text-sm font-medium">Method<select name="payment_method" class="field mt-1"><option value="cash">Cash</option><option value="gcash">GCash</option><option value="other">Other</option></select></label><label class="block text-sm font-medium">Reference number (optional)<input name="reference_number" class="field mt-1" placeholder="Auto-generated if left blank"><span class="mt-1 block text-xs text-slate-500">Enter the GCash transaction reference if available; otherwise the system creates one.</span></label><button class="btn-primary w-full">Record Payment</button></form></div>@endif
        <div class="panel p-5"><h2 class="mb-4 font-display text-lg font-semibold">Payment History</h2><div class="space-y-3">@forelse($order->payments as $payment)<div class="border-b border-slate-100 pb-3 text-sm last:border-0 last:pb-0"><div class="flex justify-between font-semibold"><span>{{ $payment->payment_status === 'refunded' ? 'Refund' : 'Payment' }} · ₱{{ number_format((float) $payment->amount, 2) }}</span><span class="capitalize">{{ $payment->payment_method }}</span></div><p class="text-xs text-slate-500">{{ optional($payment->paid_at)->format('M d, Y h:i A') }} · {{ $payment->refundedBy?->name ?? $payment->receivedBy->name }}</p><p class="text-xs text-slate-500">Reference: {{ $payment->reference_number }}</p>@if($payment->notes)<p class="text-xs text-slate-500">{{ $payment->notes }}</p>@endif
        @if(auth()->user()->role === 'admin' && in_array($payment->payment_status, ['paid', 'partially_paid'], true))
            @php($refundedForPayment = $payment->refunds->sum('amount'))
            @php($refundable = max(0, (float) $payment->amount - (float) $refundedForPayment))
            @if($refundable > 0)<details class="mt-2"><summary class="cursor-pointer text-xs font-semibold text-red-700">Refund payment</summary><form method="POST" action="{{ route('orders.payments.refund', [$order, $payment]) }}" class="mt-2 space-y-2">@csrf<input name="amount" type="number" min="0.01" max="{{ $refundable }}" step="0.01" class="field" placeholder="Up to ₱{{ number_format($refundable, 2) }}" required><input name="notes" class="field" placeholder="Refund reason" required><button class="text-xs font-semibold text-red-700">Record Refund</button></form></details>@endif
        @endif</div>@empty<p class="text-sm text-slate-500">No payments recorded.</p>@endforelse</div></div>
        <div class="panel p-5"><h2 class="mb-4 font-display text-lg font-semibold">Correction History</h2><div class="space-y-3">@forelse($order->editHistories as $edit)<details class="border-b border-slate-100 pb-3"><summary class="cursor-pointer text-sm font-semibold">{{ $edit->created_at->format('M d, Y h:i A') }} · {{ $edit->changedBy->name }}</summary><p class="mt-2 text-xs text-slate-600">{{ $edit->reason }}</p></details>@empty<p class="text-sm text-slate-500">No corrections recorded.</p>@endforelse</div></div>
    </div>
</div>
@endsection
