@extends('layouts_app')

@section('content')
<div class="mb-7"><p class="mb-1 text-sm font-medium text-brand-600">Revenue from completed orders</p><h1 class="text-3xl font-bold text-slate-900">Billing & Payments</h1></div>
<div class="mb-5 grid gap-4 md:grid-cols-3">
    @foreach([['💰','Total collected','₱'.number_format($totalCollected,2),'All time revenue'],['▤','Transactions',$payments->count(),'Paid orders'],['▥','Avg per order','₱'.number_format($payments->count() ? $totalCollected / $payments->count() : 0,2),'Average ticket']] as [$icon,$label,$value,$hint])
        <div class="panel flex gap-4 p-5"><span class="flex h-10 w-10 items-center justify-center rounded-xl bg-brand-50 text-xl">{{ $icon }}</span><div><p class="text-xs uppercase tracking-wide text-slate-500">{{ $label }}</p><p class="font-display text-2xl font-bold text-slate-900">{{ $value }}</p><p class="text-xs text-slate-400">{{ $hint }}</p></div></div>
    @endforeach
</div>
<div class="panel overflow-hidden"><div class="flex items-center justify-between border-b border-slate-100 px-5 py-4"><h2 class="font-display text-lg font-semibold">Payment Records</h2><button onclick="window.print()" class="text-sm font-semibold text-brand-600">Export / Print</button></div><div class="overflow-x-auto"><table class="w-full text-left text-sm"><thead class="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th class="px-5 py-3">Order</th><th class="px-5 py-3">Customer</th><th class="px-5 py-3">Service</th><th class="px-5 py-3">Date</th><th class="px-5 py-3 text-right">Amount</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($payments as $payment)<tr><td class="px-5 py-3 font-semibold text-brand-600">TL-{{ str_pad($payment->id, 3, '0', STR_PAD_LEFT) }}</td><td class="px-5 py-3">{{ $payment->customer?->name ?? $payment->customer_name }}</td><td class="px-5 py-3">{{ $payment->services }}</td><td class="px-5 py-3 text-slate-500">{{ $payment->created_at->format('Y-m-d') }}</td><td class="px-5 py-3 text-right font-bold text-brand-700">₱{{ number_format($payment->total_price,2) }}</td></tr>@empty<tr><td colspan="5" class="px-5 py-10 text-center text-slate-500">No completed payments yet.</td></tr>@endforelse</tbody><tfoot><tr class="font-bold"><td colspan="4" class="px-5 py-3">Total</td><td class="px-5 py-3 text-right text-brand-700">₱{{ number_format($totalCollected,2) }}</td></tr></tfoot></table></div></div>
@endsection
